version: '3'
services:  # container
   
   my_mongodb:
    image: mongo
    container_name: 'my_mongodb'
    ports:
    - "27123:27017"
   
   tweepy:  # name of the container (arbitrary)
     build: ./tweepy
     volumes:
        - ./tweepy/:/app
     depends_on:
        - my_mongodb

   my_postgres:
     image: postgres:13.0
     ports:
     - 5555:5432
     env_file:
     - ./postgres.env
   
   my_etl:
     build: ./my_ETL
     volumes:
      - ./my_ETL/:/app
     depends_on:
      - my_mongodb
      - my_postgres

